version: '3.8'

services: 
  postgres:
   image: postgres:13
   environment:
    - POSTGRES_DB=movie_review
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
   ports:
    - '5434:5432'
   volumes: 
    - ./db-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "3002:80"
volumes:
  db: